### ISSUE TITLE
Activate SNMP Trapd forwarder

### ISSUE THREAD

**Issue by vincenzodnp** [opennms-forge/docker-minion#19]
Hi All,
it could be just an hint and an help to people like me that are going to use Minions are SNMP Forwarder.
Documentation lacks on this part. 
Digging into the web I found the solution: create the file _org.opennms.netmgt.trapd.cfg_ with at least this two rows: 

> trapd.listen.port = 162
> trapd.listen.interface = 0.0.0.0

To use with Docker just use file as volume to _/opt/minion/etc/org.opennms.netmgt.trapd.cfg_

> -v ./org.opennms.netmgt.trapd.cfg:/opt/minion/etc/org.opennms.netmgt.trapd.cfg

Once file copied and container restarted, Minion will forward traps to Dominions.

Thanks

**Comment by indigo423** [comment]
Thank you for sharing, to address this topic I've created [NMS-10550](https://issues.opennms.org/browse/NMS-10550) and is probably the same for Syslog which I've added here [NMS-10551](https://issues.opennms.org/browse/NMS-10551).

**Comment by indigo423** [comment]
Can we close this issue here? Cause this is more related as a documentation issue which needs to be addressed in the main project and not just in the container image build environment.

**Comment by vincenzodnp** [comment]
Sure. Going to close the issue.
Thanks for your work!
