### ISSUE TITLE
Using Off-heap Storage for Sink Messages

### ISSUE THREAD

**Issue by vincenzodnp** [opennms-forge/docker-minion#20]
Hello there.
I need to enable this feature, to keep snmp traps during disconnection from the Broker.
I followed this link: [https://docs.opennms.org/opennms/branches/develop/guide-admin/guide-admin.html#_using_off_heap_storage_for_sink_messages](https://docs.opennms.org/opennms/branches/develop/guide-admin/guide-admin.html#_using_off_heap_storage_for_sink_messages) but not luck because it seems requested feature is not available.
Thanks

My environment is: opennms-horizon-22.0.4-1 and docker-minion/22.0.4-1

ps: if you have another hint to keep traps during disconnection, I'm open to evaluate.

**Comment by indigo423** [comment]
@vincenzodnp can we move this topic to https://opennms.discourse.group/c/community-support? I'll look into this issue, but would like make sure others in the community who have a similar issue can keep track of it.
Thanks a lot for your contribution.
